spring:
  datasource:
    url: jdbc:h2:file:~/messagedb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2