version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch



    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

#      - run: gradle dependencies
#
#      - save_cache:
#          paths:
#            - ~/.gradle
#          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Gradle Tasks
          command: ./gradlew

      - run:
          name: Gradle Tasks
          command: ./gradlew build
