name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build Gradle
        run: ./gradlew

      - name: Setup SonarQube
        run: ./gradlew composeUp

      - name: Build and Test
        run: ./gradlew build

      - name: SonarQube Scan
        run: ./gradlew sonarqube

      - name: SonarQube Finish
        run: ./gradlew composeDown
